import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import LayoutProvider from "@/components/LayoutProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// Import the Roboto font with variable configuration
const roboto = Roboto({
	subsets: ["latin"],
	weight: ["100", "300", "400", "500", "700", "900"],
	style: ["normal", "italic"],
	display: "swap",
	variable: "--font-roboto", // Define a custom CSS variable for the font
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${roboto.variable} antialiased`} // Use the custom font variable
			>
				<LayoutProvider>{children}</LayoutProvider>
			</body>
		</html>
	);
}